### ISSUE TITLE
DatadogCredentials should not be mandatory in Monitors

### ISSUE THREAD

**Issue by hlascelles** [NomadBlacky/cdk-datadog-resources#96]
DatadogCredentials should not be mandatory in monitors, and possibly elsewhere.

CloudFormation extensions can define a JSON block that is "injected" into stacks, and that can refer to the secrets. The Datadog configuration schema does indeed do this:

![image](https://user-images.githubusercontent.com/299102/158369104-f820bc74-c863-4214-8196-c77c4485f811.png)

eg, once this is defined in the AWS console, then credentials are not needed to be in the stack.

```json
{
 "DatadogCredentials": {
   "ApiKey": "{{resolve:secretsmanager:datadog-cloudformation-extensions:SecretString:api-key}}",
   "ApplicationKey": "{{resolve:secretsmanager:datadog-cloudformation-extensions:SecretString:application-key}}",
   "ApiURL": "https://api.datadoghq.eu"
 }
```

**Comment by hlascelles** [comment]
Still valid.

**Comment by hlascelles** [comment]
Still valid!

**Comment by HenrikFricke** [comment]
+1

**Comment by hlascelles** [comment]
@NomadBlacky what do you think? Can we make them optional?

**Comment by lenfree** [comment]
+1

**Comment by hlascelles** [comment]
Definitely still needed.

**Comment by hlascelles** [comment]
This is still right/needed @NomadBlacky.
